#:include "constants.kv"
#:include "widgets/widgets.kv"
#:include "screens/screens.kv"

#:import MenuScreen screens.menu.MenuScreen
#:import GameConfigScreen screens.game_config.GameConfigScreen
#:import TeamConfigScreen screens.team_config.TeamConfigScreen
#:import MainGameScreen screens.main_game.MainGameScreen

ScreenManager:
  MenuScreen:
  TeamConfigScreen:
  GameConfigScreen:
  MainGameScreen:
