#:include "constants.kv"
#:include "widgets/widgets.kv"
#:include "screens/screens.kv"

#:import MenuScreen screens.menu.MenuScreen
#:import GameConfigScreen screens.game_config.GameConfigScreen
#:import TeamConfigScreen screens.team_config.TeamConfigScreen
#:import WinnerScreen screens.winner.WinnerScreen
#:import TestScreen screens.test.TestScreen

ScreenManager:
  MenuScreen:
  TeamConfigScreen:
  GameConfigScreen:
  TestScreen:
